# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phomv < Formula
  desc "High-performance CLI that organizes photos into a YYYY/YYYY_MM/YYYY_MM_DD hierarchy from EXIF metadata"
  homepage "https://github.com/phomv/phomv"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phomv/phomv/releases/download/v0.1.2/phomv-0.1.2-darwin-amd64.tar.gz"
      sha256 "eac119583d87663c101097b25fc7297430b85c432e6e6d772b860d24ab7489c9"

      define_method(:install) do
        bin.install "phomv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phomv/phomv/releases/download/v0.1.2/phomv-0.1.2-darwin-arm64.tar.gz"
      sha256 "1b85d3fbe7e5cf605c49573bf27243925ab7135ee49eec47239a7c01ea54022f"

      define_method(:install) do
        bin.install "phomv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phomv/phomv/releases/download/v0.1.2/phomv-0.1.2-linux-amd64.tar.gz"
      sha256 "bdaf1ed0a79a69fdb6d7f5f58a90ad422f7d4edb95628437ff3a1dcdf35ca8b7"
      define_method(:install) do
        bin.install "phomv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phomv/phomv/releases/download/v0.1.2/phomv-0.1.2-linux-arm64.tar.gz"
      sha256 "d4bd3ce8083ebae4ea845f7ac889bde297fbf31780f25214c2cc23891b784e31"
      define_method(:install) do
        bin.install "phomv"
      end
    end
  end

  test do
    system "#{bin}/phomv", "version"
  end
end
