# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phomv < Formula
  desc "High-performance CLI that organizes photos into a YYYY/YYYY_MM/YYYY_MM_DD hierarchy from EXIF metadata"
  homepage "https://github.com/phomv/phomv"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phomv/phomv/releases/download/v0.1.1/phomv-0.1.1-darwin-amd64.tar.gz"
      sha256 "5e1d14be99807831e612ca8f914a87ec981cab78fb83e98029a52239b4f86590"

      define_method(:install) do
        bin.install "phomv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phomv/phomv/releases/download/v0.1.1/phomv-0.1.1-darwin-arm64.tar.gz"
      sha256 "c84a0b4eb81da625121f366f2ae33dc5f9567f489b22489202665fe79d97feae"

      define_method(:install) do
        bin.install "phomv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phomv/phomv/releases/download/v0.1.1/phomv-0.1.1-linux-amd64.tar.gz"
      sha256 "30b1ff06e57d5419430febcf59901c9166dd2f8b29a2528c853036d1fc5a792c"
      define_method(:install) do
        bin.install "phomv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phomv/phomv/releases/download/v0.1.1/phomv-0.1.1-linux-arm64.tar.gz"
      sha256 "acbb70cb563056bd6ca311e97f733c0f6a35f712fdd23e131db427be2ad7bff9"
      define_method(:install) do
        bin.install "phomv"
      end
    end
  end

  test do
    system "#{bin}/phomv", "version"
  end
end
